### PR TITLE
Title hierarchy fixes

### PR DESCRIPTION
**Pull request by bgsmase**
Addresses #8 .

This doesn't necessarily make the structure correct but it makes the hierarchy of sections of the current document get reflected in the collapsible contents list in the left-hand bar so it will be easier to do further changes later.

It is relevant for #6 although not fixing it as it makes some of the example data sections appear in the left-hand contents list.

### CODE REVIEW

**Comment by nmtoken** [comment]
Looks better.

One nesting issue I can see for fixing later is http://.../providingdata.html#layer-coverage-feature-metadata should be a child of http://.../providingdata.html#onegeology-profile

**Comment by nmtoken** [comment]
Not sure if `Move server software sections inside web services ` is working quite as described.  on LHS menu, the Using [software name] sections are not showing inside 'web services'

**Comment by bgsmase** [comment]
@nmtoken I think you may be building from the master branch instead of the temp/title_hierarchy_fixes branch which is the one that is being requested to merge in to master in this pull request.

**Comment by bgsmase** [comment]
Or you may need to do a make clean before make html if you built from different branch before as sometimes just new pages get regenerated but not the hierarchy if the other pages haven't been changed.

**Comment by nmtoken** [comment]
Looks like you're correct, I can see looking at the raw code that those changes have been made, I thought I had the temp/title_hierarchy_fixes branch, but have gone wrong somewhere

**Comment by nmtoken** [comment]
Have it now.  definitely better.  GeoSciML nested under OneGeology profile is not correct though; not sure where that content should go.  Possibly, Level 2 involvement with OneGeology web services?

**Comment by bgsmase** [comment]
I agree about the GeoSciML section which has been taken from the main web site pages. I propose to merge this now anyway so the structure is clearer and then we can discuss further reorganisation after that.

**Pull request merged**
